### ISSUE TITLE
Some bug for fake stattrak.

### ISSUE THREAD

**Issue by xSuspect** [BeepIsla/fake-stattrak#1]
1.Does not download automatically [https://prnt.sc/rhaitv] if you manually set it works.

**Comment by BeepIsla** [comment]
I did not actually test the protobuf downloader. I have fixed the issue (eecb3219778bbefaa21a533df8af7e1b28379909), It should work now.

**Comment by BeepIsla** [comment]
Since there are no further reports of this happening I am going to assume this has been successfully fixed.
