### ISSUE TITLE
[TF2] Stats not changing

### ISSUE THREAD

**Issue by Play3rBust3r** [BeepIsla/fake-stattrak#11]
I just tried this and it didn't work.
I had 617 kills before and now i have the same kills (I got the succesfull message so yeha, it should have worked)

**Comment by BeepIsla** [comment]
Show your config (**Censor account username and password first**)

**Comment by Play3rBust3r** [comment]
> Show your config (**Censor account username and password first**)

{
	"boostingAccount": {
		"username": "MainAccount",
		"password": "MainPassword"
	},
	"botAccount": {
		"username": "BotAccount",
		"password": "BotPassword"
	},
	"itemID": "10032097344",
	"appID": 440,
	"eventType": 0,
	"incrementValue": 500,
	"repeat": 1
}

**Comment by BeepIsla** [comment]
Try `repeat` `500` and `incrementValue` `1`. The `eventType` you are using `0 (Kills)` does not support incrementt.

**Comment by Play3rBust3r** [comment]
I had to use `null` and not `1` in `incrementValue` in conjunction with `repeat: "desired number".` It kinda makes sense because kills already count as `1`, so there's no need to tell the game to add 1 kill again.

**Comment by uhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
I have this same issue, I tried setting it to "null" but it still doesn't work for me
