### ISSUE TITLE
Program is running fine but no kills are applied.

### ISSUE THREAD

**Issue by proton298** [BeepIsla/fake-stattrak#12]
Hey,

I have installed all the dependencies that are listed on README, I write the config json and then with both accounts logged out, I run the script and everything seems to be working fine, and it reaches that part that it will disconnect after 10 seconds and then sucessfully disconnects, but the kills are never applied to the strange item.

I am trying to use it for tf2 and I am running win10.  

This is the bottom part of the properties file : 
```
	"itemID": "10148665608",
	"appID": 440,
	"eventType": 0,
	"incrementValue": 100000,
	"repeat": 1
```
This is the powershell output : 
```
PS C:\Users\pc\Desktop\fake-stattrak-master> node .\index.js
Validating protobufs...
Found protobufs!
Requiring files for appID 440
Creating constructors...
Logging into Steam as client and server...
Successfully logged into Steam and signed up as bot account as 76561198450758517
Successfully logged into Steam and signed up as main account as 76561198436221822
Successfully logged into Steam and signed up as server as 90146753008516096
Fake joining server with bot account 76561198450758517...
Successfully added player to server, verifying on client...
Successfully connected client and server!
Fake joining server with bot account 76561198436221822...
Successfully added player to server, verifying on client...
Successfully connected client and server!
Item increments are now being processed by Valve, this may take a little bit or until log-off.
Logging off in 10 seconds...
Successfully logged off
```

**Comment by BeepIsla** [comment]
You can't use `incrementValue` with kills, only for stuff like heals. Try setting `incrementValue`  to either `1` or `null` and set `repeat` to like `100000` instead

**Comment by proton298** [comment]
Oh it worked by setting it to null and the repeat to 100 000.
Thank you for your very quick reply
