### ISSUE TITLE
CSGO ST doesn't boostings

### ISSUE THREAD

**Issue by oxyGodmode** [BeepIsla/fake-stattrak#14]
https://imgur.com/a/Wzu2d6V

I tried everything, constantly changed the repeat values , something turned out 1 time, as a result, 1 kill, and no longer works, I only achieved the XD limit
in tf2 everything works fine, I don't know why
maybe I'm doing something wrong?

**Comment by BeepIsla** [comment]
Try `incrementValue: 1` and `repeat: 1000` or any other `repeat` value.

**Comment by oxyGodmode** [comment]
Yes, this is for weapon(scar)

**Comment by oxyGodmode** [comment]
If i set incrementValue: 1 , then and set repeat : 100/1000 , i got only 1 kill : https://imgur.com/a/6Ry7wo6

if i set incrementValue: null , nothing happened.

if i set incrementValue: 1 and repeat 1/100/1000/100000, the same i got 1 kill : https://imgur.com/a/SMXEbGr

**Comment by BeepIsla** [comment]
Yeah, looking at the source code. Turns out CSGO doesn't use repeating at all. At least it works now.
