### ISSUE TITLE
Possibility with Steamworks

### ISSUE THREAD

**Issue by iebb** [BeepIsla/fake-stattrak#18]
Was trying to rewrite this using Steamworks API, however I'm stucked at implementing
`this.client.gamesPlayed({steam_id_gs: serverID, game_id: this.appID});`, which seems critical for this thing to work.

Are there any clues on it, or that's impossible via Steamworks, or it's a server-side thing?

**Comment by BeepIsla** [comment]
As far as I know Steamworks does almost everything automatically behind the scenes. On the client you just need `ISteamUser::GetAuthSessionTicket` and send it to the server, the server then just needs to call `ISteamGameServer::BeginAuthSession` and from that point on-wards Steam knows which server the client is on. The only thing that needs to be done now is using the GameCoordinator to send the modify-item protobufs
