### ISSUE TITLE
Is this still work in tf2?

### ISSUE THREAD

**Issue by animetiddies69** [BeepIsla/fake-stattrak#23]
I tried this like half year ago and it was working flawessly. Now it's just doesnt. Am i doing something wrong here? Maybe bot account should be premium or something? Kills just never apply.
![imagine farming up sniper melee](https://user-images.githubusercontent.com/107907676/174721251-35bbe6fc-e7b3-442a-a35b-0c4daf51a08a.jpeg)

**Comment by BeepIsla** [comment]
I haven't use it in ages so I am not sure, maybe `"incrementValue": null` works?

**Comment by animetiddies69** [comment]
I'll be honest with you, i'm kinda retarded and don't know anything about scripts stuff and barely googled how node js is even works. As far as i understand, incrementvalue should be always 1, repeat is the number how many kills you wanna get in one go. The limit used to 300k, i think.
Yeah, i remember why i stop using this. I farmed about six millions kills on my spy's revolver and it's stopped working. Maybe there are some hidden ban for doing this.
Anyway, incrementValue": null doesn't work as well.

**Comment by BeepIsla** [comment]
`incrementValue` is usually used for things like healing where large amounts can happen in one go (Like Crusader's Crossbow healing like 80+ in one shot), `repeat` is basically just duplicating the same request multiple times for things which do not support `incrementValue` (Like Kills).

I got so many kills on one of my CSGO skins that it wrapped back around to 0 and it still worked, so I don't think there is some kind of ban for it. I will try it out and see if it works.

**Comment by BeepIsla** [comment]
I am back! It works for me, I even applied it to a War Paint directly instead of to a weapon. The bot account I used is a F2P account so I doubt that is the issue. this is my config:
```json
{
	"itemID": "9029694193",
	"appID": 440,
	"eventType": 0,
	"incrementValue": 1,
	"repeat": 1000
}
```

Although I have to also say that the version I have my on PC and the version here on Github are slightly different, I wanted to add an interface ages ago but never actually did it. I have now updated this repository, it is now exactly as it is on my PC. Please delete what you have and download it again.

**Comment by animetiddies69** [comment]
Still nothing. I doubt that i'm doing something wrong, it's just not working for me. I guess i'll have to accept it.
![5](https://user-images.githubusercontent.com/107907676/174730611-0645c452-20ef-4737-830d-0afe9842c436.jpg)

**Comment by BeepIsla** [comment]
That is very weird, I sadly don't know what the reason could be

**Comment by animetiddies69** [comment]
Maybe i'm wrongly using powershell? I unpack files on my C disk, then use powershell by typing it in short menu of windows. Usual one, without administrator permission. 
I was using this back then for few days and it suddenly stopped working, i didn't change anything.

**Comment by BeepIsla** [comment]
Shouldn't matter, maybe you have the wrong ItemID or the wrong Account in "boostingAccount"?

**Comment by animetiddies69** [comment]
Then it woundn't work at all. As you can see, it seems like they actually doing it. Both accounts joining the game.
Try it if you want, i'll type steam guard code here once i get it. Please don't steal my hats :(
{
	"boostingAccount": {
		"username": "loyenss",
		"password": "HDS24Tdabest1337"
	},
	"botAccount": {
		"username": "healslutty",
		"password": "13372281488Qq"
	},
	"itemID": "11759429351",
	"appID": 440,
	"eventType": 0,
	"incrementValue": 1,
	"repeat": 100000
}

**Comment by BeepIsla** [comment]
You should change your passwords right now. This is a public issue list and anyone can read it.

**Comment by animetiddies69** [comment]
I don't know how to make personal hide or something like that. Anyway i don't care for alt account and boosting one is steam guarded.
So, can you help me with this?

**Comment by BeepIsla** [comment]
I told you everything I know, what is your SteamID64 and is your inventory public? I would want to check if the ItemID is correct.

**Comment by animetiddies69** [comment]
https://steamcommunity.com/id/96_/inventory/#440_2_11759429351
11759429351

**Comment by BeepIsla** [comment]
I just bought one myself and it works fine for me, I have no idea what could be causing this. Sorry I can't help any further with this.
