### ISSUE TITLE
Why _steamid "90071992547409920" is Anon Gameserver?

### ISSUE THREAD

**Issue by AidarSource** [BeepIsla/fake-stattrak#24]
I'm interested, why `_steamid "90071992547409920"` is Anon Gameserver here? Isn't `"90071992547409920"` is steamid of some guy? lol

In case of GSLT tokens, what `_steamid` it'll be?

https://github.com/BeepIsla/fake-stattrak/blob/e954c99eaa06a9258fbe55b9e589bad299e06918/components/Server_Shared.js#L105

**Comment by BeepIsla** [comment]
Different SteamIDs exist based on some things encoded within the 64bit number. You can see a SteamID breakdown here: https://steamid.f1ssi0n.com/

Users' SteamID usually starts with a 7, anonymous gameservers with 9, and GSLT gameservers with 8

**Comment by AidarSource** [comment]
> Different SteamIDs exist based on some things encoded within the 64bit number. You can see a SteamID breakdown here: https://steamid.f1ssi0n.com/
> 
> Users' SteamID usually starts with a 7, anonymous gameservers with 9, and GSLT gameservers with 8.
> 
> I believe a non-logged in GSLT would be `85568392920039424` but I am not 100% sure

ow, that was interesting! So to log in with GSLT we need to give it to another argument of `_logOnDetails`?

**Comment by BeepIsla** [comment]
I don't think steam-user properly supports logging in with a GSLT, if I remember correctly its broken

**Comment by AidarSource** [comment]
> I don't think steam-user properly supports logging in with a GSLT, if I remember correctly its broken

oh, thats why. With non-logged in GSLT `85568392920039424` parameter will give you `InvalidParam` too

**Comment by AidarSource** [comment]
@BeepIsla Can I ask about `obfustucated_private_ip`, and `cell_id`? Its interesting too.
In case of `cell_id`, I know that Steam is dividing world to cells, but where you got those numbers?

https://github.com/BeepIsla/fake-stattrak/blob/e954c99eaa06a9258fbe55b9e589bad299e06918/components/Server_Shared.js#L108

**Comment by BeepIsla** [comment]
https://github.com/DoctorMcKay/node-steam-user/blob/698fa95c38237ad389b3a495f00e9f7c7308192d/components/08-logon.js#L40-L49

If I remember correctly the number I used is just 127.0.0.1 so localhost or something like that for no partiular reason

**Comment by AidarSource** [comment]
Thanks a lot!
