### ISSUE TITLE
[Question] TF2 strange farmer.

### ISSUE THREAD

**Issue by oxyGodmode** [BeepIsla/fake-stattrak#25]
![image](https://user-images.githubusercontent.com/87392051/195169047-30105d8b-e918-4205-aa2b-07ad0e9a7d5b.png)
How do I make it so that I can get more value than 300000 at a time?
If I write "repeat": at least more than 300001, it does not work, it shows that everything is successful, logged off, but nothing happens, I met one person who has 77 million on 20+ guns, and wherever there are additional counters the same number, he can't be so long all 300k times to run the script for what?
For example: https://steamcommunity.com/id/goodgalRiRi/inventory/#440 (just look , that's amazing, LOL)
![image](https://user-images.githubusercontent.com/87392051/195171879-b51c825d-21d8-49f0-8b0e-30d312eb4668.png)
![image](https://user-images.githubusercontent.com/87392051/195171969-7874c6d4-2dff-4a59-9e73-ef51285acff8.png)
![image](https://user-images.githubusercontent.com/87392051/195172030-4e4fdc52-59c3-4a65-a92e-04589dc0b716.png)
![image](https://user-images.githubusercontent.com/87392051/195172099-f1e75d28-fba6-4f9e-b329-a44addfa0dd4.png)

**Comment by BeepIsla** [comment]
The script isn't perfect. There are lots of things to optimize. It could simple be the TF2 backend detecting spam and blocking it or something. I can look into it some time later and see if I can hopefully make it better.

**Comment by oxyGodmode** [comment]
Kay, im waiting, bro.

**Comment by BeepIsla** [comment]
I have done a few of changes to the code. It should work a lot better now for large amounts. Download again and see if this solves your problem.

**Comment by oxyGodmode** [comment]
IDK What's im doing wrong, but
![image](https://user-images.githubusercontent.com/87392051/195881898-ac30faea-9eb6-4efb-bcda-adf95d85fc0d.png)
![image](https://user-images.githubusercontent.com/87392051/195881931-f3b0ddb6-ecd2-445a-a6d1-7a03bdde6b55.png)
![image](https://user-images.githubusercontent.com/87392051/195882018-d706e3f6-3395-4841-b2f5-8e96c40ccb1d.png)

**Comment by BeepIsla** [comment]
I noticed when testing not all increases are applied properly but I never had to be off by that much. I will look again and try with 15M to see what happens, hopefully I can optimize it

**Comment by BeepIsla** [comment]
I did some changes and 15 million went through without problems. Try again!

**Comment by oxyGodmode** [comment]
> I did some changes and 15 million went through without problems. Try again!

Lemme try

**Comment by BeepIsla** [comment]
If you copy the link printed on the third line from bottom does it pre-select the correct item in your inventory?

**Comment by oxyGodmode** [comment]
Yes! On my mask, now i trynna to my sniper rifle....
It's different from event type 64(point scored) to 0(strange)
![image](https://user-images.githubusercontent.com/87392051/196473053-40a907ae-2f7b-4398-93c5-5f535e39b3b6.png)

**Comment by oxyGodmode** [comment]
Strange, but my cosmetic still have 300k points, since i create a this thread. Now im awaiting when the script will finished for farm my sniper rifle.

**Comment by oxyGodmode** [comment]
![image](https://user-images.githubusercontent.com/87392051/196476634-10789f8d-a5ff-4d36-a8ab-b4532d7d80d9.png)

**Comment by oxyGodmode** [comment]
No new updates?!
