### ISSUE TITLE
Didn't have this error before and how can i fix it?

### ISSUE THREAD

**Issue by zerefoex** [BeepIsla/fake-stattrak#26]
PS C:\Users\User\Desktop\fake-stattrak-master> node index.js
Validating protobufs...
Failed to find protobufs, downloading...
(node:22024) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ReferenceError: body is not defined
    at Helper.downloadProtobufs (C:\Users\User\Desktop\fake-stattrak-master\helpers\Helper.js:42:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\User\Desktop\fake-stattrak-master\index.js:37:3
Failed to download protobufs.

**Comment by BeepIsla** [comment]
Sorry my mistake. Download again, It should be fixed now.

**Comment by zerefoex** [comment]
Works thx
