### ISSUE TITLE
Question: IncrementValue progress kill

### ISSUE THREAD

**Issue by x0xlqaxqx3xaxax** [BeepIsla/fake-stattrak#27]
How can i increase kill progress more and more faster
P.S sorry my bad english
![image](https://user-images.githubusercontent.com/118252889/201862440-f52d39d8-ff55-48cf-9d52-1ea3d0d22ce9.png)

**Comment by x0xlqaxqx3xaxax** [comment]
config
	"itemID": "27665644628",
	"appID": 730,
	"eventType": 0,
	"incrementValue": 1000000

**Comment by BeepIsla** [comment]
My script is not good but you can just leave your computer running over night
