### ISSUE TITLE
Event Listening

### ISSUE THREAD

**Issue by ezaremi** [BeepIsla/fake-stattrak#33]
node-steam-user package and node-globaloffensive with the package (logOn, tradeOffers, steamGuard, connectedToGC,connectedFromGC) some events can be listened to. Is it possible to listen to some protobufs events of a server created in this project? If possible, how can I do this?

**Comment by BeepIsla** [comment]
Your question has nothing to do with this project.

I don't know what "protobuf events" are suppose to be, everything between the client and the CSGO backend come through [the `receivedFromGC` event from steam-user](https://github.com/DoctorMcKay/node-steam-user/wiki/Game-Coordinator)
