### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by aloann** [BeepIsla/fake-stattrak#34]
once I write "node index.js" in the CMD 

I get this:

```
Validating protobufs...
Failed to find protobufs, downloading...
Failed to download protobufs.
```

I followed your instructions very well, I'm not sure if I did anything wrong but here's a screenshot of how it looks like
![image](https://user-images.githubusercontent.com/132700140/236529923-808031c1-8d7d-48f9-8644-bdefe18583ea.png)

**Comment by aloann** [comment]
Hey! Thank you so much for the quick reply, the issue is resolved and the program seems to be working <3

**Comment by BeepIsla** [comment]
Good to hear

**Comment by aloann** [comment]
Extra: 
in the `incrementValue` I put in for example 2100 (since my main intention is resetting my ST kills after re organizing my skins)

But in my inventory after 5 minutes It moved from 0 to 180 but didn't go further. Is this normal?

**Comment by BeepIsla** [comment]
There have been some weird changes the past few weeks which made it suddenly work a lot worse. I don't really have control over these

**Comment by aloann** [comment]
> There have been some weird changes the past few weeks which made it suddenly work a lot worse. I don't really have control over these

That's weird, I don't have much knowledge regarding this stuff maybe the pressure on valve servers recently due to market changes makes it hard for the inventory to track the kills since they're "too fast"?

But it was nice trying this program! I had my friend sending me this a year ago and I never bothered because it seemed hard to do with all these instructions since I always had an issue dealing with github stuff ^^''

Regardless thanks for the quick responses and your time!
