### ISSUE TITLE
can't seem to log in

### ISSUE THREAD

**Issue by TheZafkiel** [BeepIsla/fake-stattrak#35]
I have been using the version downloaded in 2022, but recently I found that some accounts cannot be logged in, so I downloaded the latest version, but I found that I still cannot log in to these accounts, can you help me check the problem

**Validating protobufs...
Failed to find protobufs, downloading...
ReferenceError: fetch is not defined
    at Function.downloadProtobufs (/app/test/helpers/Helper.js:39:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/test/index.js:37:3
Failed to download protobufs.**

When I manually downloaded protobufs from GitHub and put them in, another problem occurred

**Validating protobufs...
Found protobufs!
Requiring files for appID 730
Creating constructors...
Logging into main account...
Steam Guard App Code: ****
/app/test/components/Client_Shared.js:116
                                                reject(new Error("Failed to connect to Steam"));
                                                       ^

Error: Failed to connect to Steam
    at /app/test/components/Client_Shared.js:116:14**

and sometimes is

**Validating protobufs...
Found protobufs!
Requiring files for appID 730
Creating constructors...
Logging into main account...
/app/test/helpers/Helper.js:19
                let res = await fetch(uri.href);
                          ^

ReferenceError: fetch is not defined
    at Function.getJSON (/app/test/helpers/Helper.js:19:13)
    at Function.GetSteamAPI (/app/test/helpers/Helper.js:9:25)
    at /app/test/components/Client_Shared.js:65:32
    at new Promise (<anonymous>)
    at CSGOClient.login (/app/test/components/Client_Shared.js:63:10)
    at /app/test/components/Client_730.js:12:28
    at new Promise (<anonymous>)
    at CSGOClient.login (/app/test/components/Client_730.js:10:10)
    at /app/test/index.js:61:19
    at Object.<anonymous> (/app/test/index.js:105:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47**

I have conducted some tests. The account that has not opened the steam token or has not updated the new version of steamapp can be used normally when logging in, but various errors will appear when logging in to the account that has updated the new version of steamapp.

Thanks for your  reply and your precious time!

**Comment by BeepIsla** [comment]
Update NodeJS, you are running an ancient version

**Comment by TheZafkiel** [comment]
thank you for your reply! I'm glad to see it's working now.
But it seems that there are still some problems. When I set the incrementValue to 5000, the log tells me that it has been Progress: 5000 / 5000, but when I wait for a few minutes and check the inventory, it only increases by more than 200

**Comment by TheZafkiel** [comment]
When I put "incrementValue": 100500, after waiting for several minutes, it increased by about 3.6k

**Comment by BeepIsla** [comment]
This is an issue with the CSGO backend, it disallows spamming StatTrak increments too much, there is not much I can do. Its been mentioned in https://github.com/BeepIsla/fake-stattrak/issues/30 and https://github.com/BeepIsla/fake-stattrak/issues/31

**Comment by TheZafkiel** [comment]
Thank you for your answer! you are a good developer
