### ISSUE TITLE
TF2 kills doesn't work

### ISSUE THREAD

**Issue by KingTerrytheTerrible** [BeepIsla/fake-stattrak#5]
The kills for stranges require CMsgIncrementKillCountAttribute instead of CMsgIncrementKillCountAttribute_Multiple or batched.

**Comment by BeepIsla** [comment]
It should work. A `CMsgIncrementKillCountAttribute_Multiple` is just multiple of `CMsgIncrementKillCountAttribute`. Try setting `incrementValue` to `1` (or `null` I don't remember, try both) and `repeat` to something like `1000`.

**Comment by KingTerrytheTerrible** [comment]
Having it set to null did it, thanks.
