### ISSUE TITLE
Bot open connect on server csgo

### ISSUE THREAD

**Issue by botoboua** [BeepIsla/fake-stattrak#8]
Is it possible to create a bot that knows how to connect to a real server? In order for the steam server browser (search for community servers) to see the connection to the server and report that there is 1 player on the server. It is not necessary to hold such a connection for a long time, is it just possible to do this?

**Comment by BeepIsla** [comment]
Yes its possible. Enjoy making that yourself.

**Comment by botoboua** [comment]
I want to hire you $ to do this for me. If you have a little time, please contact me naykonc7@gmail.com

**Comment by BeepIsla** [comment]
No.

**Comment by botoboua** [comment]
I'm sorry, I hope you change your mind. Please tell me how to connect to the server through a bot? So that he can establish a connection to the server ... I've been looking for a solution for a week now, maybe it's on the surface?

**Comment by BeepIsla** [comment]
Look [at the leaked CSGO source code](https://github.com/perilouswithadollarsign/cstrike15_src/) and replicate what it does. Its all written out for you by Valve, you just have to convert it into the programming language of your choice. Enjoy learning, end of the conversation.

**Comment by botoboua** [comment]
Thank. I will ask another stupid question as an expert in this area. I understand the work plan correctly: (I will write in C ++, i.e. this language is the most understandable for me).

1. We connect to the Steam account (login | password | secret code) - is in your example.
2. Launch the CSGO game. (We simulate the launch) - Using GameCoordinator?
3. We disassemble the sources and make a connection to the game server - IP: PORT

I promise not to bother you anymore, give a detailed answer, I'm just learning)

**Comment by BeepIsla** [comment]
I don't know myself. You must read what CSGO does and replicate it.
