### ISSUE TITLE
Steam authorization inside the program for SteamAPI_Init ()

### ISSUE THREAD

**Issue by jojomojo23** [BeepIsla/fake-stattrak#9]
Hi, my application works with SteamAPI_Init (), for successful operation you need to have an authorized (login | password) Steam client next to the program. Can you please tell me if it is possible to authorize Steam inside my application so that I do not have to keep an open Steam nearby?

**Comment by BeepIsla** [comment]
If `SteamAPI_Init()` runs for the app ID `730`/`440` (CSGO/TF2) then yes. Just generate an authentication ticket and authorize it on the server. Read the [P2P or Game Servers section](https://partner.steamgames.com/doc/features/auth#P2P-or-Game-Servers) on the Steamworks Developer Documentation.

**Comment by jojomojo23** [comment]
Thank you very much, you are a good programmer and an excellent person <3, if I have any questions, let me write to you here again =)

**Comment by jojomojo23** [comment]
Please allow me to check with you by examining https://partner.steamgames.com/doc/features/auth#P2P-or-Game-Servers - I can arrange Steam profile authorization directly in my program and use functions such as - SteamMatchmakingServers () -> RequestInternetServerList (SteamUtils () -> GetAppID (), & pFilter, ARRAYSIZE (pFilters), this); without SteamAPI_Init ()?

Forgive me for asking (clarifying), just difficulties in translation.

**Comment by jojomojo23** [comment]
I don’t understand how to log in. Which function accepts the login / password from Steam? I did not find this in the documentation (

sorry for smap(

**Comment by BeepIsla** [comment]
I am not here to teach you how to program or teach you how to read documentation. `SteamAPI_Init()` is required for all Steam functionality to happen, it connects to your local Steam Client. You never login with Steamworks.

**Comment by jojomojo23** [comment]
I understand your irritability by my questions (sorry for that). My program works correctly only when Steam is running, but Steam can only be launched once, and I need to use my program on several Steam accounts at once. Please advise how can I simulate the work of Steam several times so that I can run several copies of my program, each of which will work in isolation with a specific Steam account?

**Comment by jojomojo23** [comment]
Maybe you can advise a forum where I can ask such a question and help me?

**Comment by BeepIsla** [comment]
Use a Virtual Machine, a Sandbox, or just don't and use a proper Steam Client library for whatever language you are using. I don't know what your goal is but this is widely off-topic and unrelated to this project.

I don't know why you opened an issue here about something so unrelated. I don't have any resources or forums for you, just learn the programming language of your choice and you eventually pick things up over time when using it regularly.
